name: Build and Upload as encrypted artifact

on: 
  workflow_dispatch:

jobs:
  build:
    name: Building for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          path: Lumis_Constellations
          repository: Pydes-boop/Lumis_Constellations # Change title for other workflows
          token: ${{ secrets.ACCESS_TOKEN_LUMI }}

      - name: Cache files for faster build
        uses: actions/cache@v4
        with:
          path: Lumis_Constellations/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Build project with unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: auto
          projectPath: ./Lumis_Constellations/
          versioning: Semantic
          buildName: Lumis_Constellations # Change title for other workflows

      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          path: ./extern
          sparse-checkout: scripts
          sparse-checkout-cone-mode: false

      - name: Zip folder
        run: ./extern/scripts/zip.sh
        env:
          FOLDER: ./Lumis_Constellations/build

      - name: Encrypt build
        run: ./extern/scripts/encrypt.sh
        env:
          PASSPHRASE: ${{ secrets.ARTIFACTS_PASSPHRASE }}
          FILE: ./Lumis_Constellations/build.zip

      - name: Overview
        run: |
          ls
          echo "--- cd ---"
          cd Lumis_Constellations
          ls
          echo "--- cd ---"
          cd ..
          echo "--- cd ---"
          cd extern
          ls
          echo "--- cd ---"
          cd scripts
          ls
          cd ..
          cd ..
          
      - name: Upload build results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lumis_Constellations-${{ matrix.targetPlatform }} # Change title for other workflows
          path: ./Lumis_Constellations/Build.zip.enc
