name: Generating, Zipping and Encrypting a folder/file

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    name: Testing zipping and encryption
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Create folder
        run: |
          mkdir test
          cd test
          touch testingfile
          ls
          cd ..
          ls

      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          path: ./extern
          sparse-checkout: scripts
          sparse-checkout-cone-mode: false

      - name: Zip folder
        run: ./extern/scripts/zip.sh
        env:
          FOLDER: test

      - name: Encrypt build
        run: ./extern/scripts/encrypt.sh
        env:
          PASSPHRASE: ${{ secrets.ARTIFACTS_PASSPHRASE }}
          FILE: ./test.zip

      - name: Overview
        run: |
          ls
          
      - name: Upload build results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testing_file
          path: test.zip.enc
