name: Build game for different platforms

on: workflow_dispatch
  
jobs:
  build-Windows:
    name: Building Lumis_Constellations for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
          - WebGL
    steps:
      - name: Echo the string
        run: |
          echo "My string is: $REPO_NAME"
          
      - name: Checkout private repository # TODO work and improve this
        uses: actions/checkout@v4
        with:
          repository: Pydes-boop/Lumis_Constellations
          token: ${{ secrets.ACCESS_TOKEN_LUMI }}

      # Cache files for faster build
      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Build Project with unity
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: auto
          projectPath: .
          versioning: Semantic
          buildName: Lumis_Constellations
          
      # Upload Build as Artifact
      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: Lumis_Constellations_0.0.${{ github.run_number }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      

      # Deploy
      # - name: Upload build to itch.io
      #   uses: robpc/itchio-upload-action@v1
      #   with:
      #     path: build
      #     project: ${{ secrets.ITCH_PROJECT }}
      #     channel: webgl
      #     api-key: ${{ secrets.ITCH_API_KEY }}
      #     version: ${{ env.RELEASE_DATE }}-${{ env.SHORT_HASH }}
