name: Build game for different platforms

on: workflow_dispatch
  
jobs:
  build-and-publish:
    name: Building Lumis_Constellations for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
          - WebGL
    steps:
      # Checkout private game repository
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: Pydes-boop/Lumis_Constellations
          token: ${{ secrets.ACCESS_TOKEN_LUMI }}

      # Cache files for faster build
      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Build Project with unity
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: auto
          projectPath: .
          versioning: Semantic
          buildName: Lumis_Constellations
          
      # # Upload Build as Artifact
      # - name: Upload build results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Lumis_Constellations_0.0.${{ github.run_number }}-${{ matrix.targetPlatform }}
      #     path: build/${{ matrix.targetPlatform }}

      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: ${{ matrix.targetPlatform }}
          ITCH_GAME: test-environment
          ITCH_USER: pydes
          PACKAGE: build/${{ matrix.targetPlatform }}
